### ISSUE TITLE
Not load photo

### ISSUE THREAD

**Issue by AgalakovDV** [KerimovElchin/Lips#2]
![image](https://user-images.githubusercontent.com/61158013/76022920-2793e580-5f39-11ea-80ef-2237a617e9f2.png)
![image](https://user-images.githubusercontent.com/61158013/76022979-47c3a480-5f39-11ea-8303-6ce9b52e4d71.png)

**Comment by KerimovElchin** [comment]
Fixed by https://github.com/KerimovElchin/Lips/commit/d38b075ee3aa80b3e5b1d1d7a788c248d5f0f1e1
